INSERT INTO shelter.animals (id_animal, name, arrival_date, description, breed_id, size_id) VALUES (1, 'Goran', '2016-09-24', 'Ten pies to wulkan energii, świetnie aportuje – może godzinami biegać za piłką. Idealny dla osób aktywnych, które szukają psiego kompana do np. górskich wycieczek, biegania itd. Zna podstawowe komendy i powoli uczy się, że szczekaniem nic nie osiągnie, ale trzeba być bardzo konsekwentnym. Raczej powinien być jedynym psem w domu, ale nie należy tego mylić z całkowita izolacją od innych psów. Mimo swojego temperamentu i ciężkiego charakteru, naprawdę można go polubić - wszystko robi z pełnym zaangażowaniem. Na pewno przed adopcją trzeba go dobrze poznać, Goran po prostu potrzebuje odpowiedniego opiekuna.
Do tej pory nie miał szczęścia do ludzi, wpierw trafił do nas poważnie pogryziony - nikt wtedy po niego się nie zgłosił. Był adoptowany jako jeszcze młody psiak - jednak wbrew zapewnieniom nikt się nim nie zajmował, nie zapewnił ani wychowania, ani spacerów i Goran z nudów sam znalazł sobie zajęcie, niszczył ogrodzenie oraz niestety uśmiercił kilka kur. Dlatego został zwrócony. Kolejny dom też okazał się nieodpowiedni.
Nie jest to stary pies, ale ze względu na ''staż'' w Schronisku zalicza się do weteranów :(', 2, 3);
INSERT INTO shelter.animals (id_animal, name, arrival_date, description, breed_id, size_id) VALUES (3, 'Kordek', '2018-04-19', 'Płochliwy psiak, który dopiero w schronisku uczy się jak powinny wyglądać relacje z ludźmi. Powoli uczy się chodzić na smyczy. Nie lubi dotyku, ale w stosunku do ludzi których zna powoli się otwiera, cieszy się na wspólne spacery. Potrzebuje cierpliwego opiekuna.', 2, 3);
INSERT INTO shelter.animals (id_animal, name, arrival_date, description, breed_id, size_id) VALUES (4, 'Rudi', '2018-05-03', 'Najlepiej będzie się czuł w domu z ogrodem. Preferowany dom bez dzieci. Pewny siebie, energiczny. Potrzebuje doświadczonego opiekuna. Sprawdzi się w psich sportach.', 2, 3);
INSERT INTO shelter.animals (id_animal, name, arrival_date, description, breed_id, size_id) VALUES (5, 'Lary', '2018-06-26', 'Średniej wielkości uroczy kundelek. Lubi spacery, na wybiegu zawsze musi sprawdzić informacje pozostawione przez inne psiaki ;) Ładnie przychodzi na zawołanie. Kocha dobrze zjeść, co ułatwia nawiązywanie z nim przyjaźni. Potrzebuje opiekuna obytego w opiece nad psami. Nieufny w stosunku do obcych – potrzebuje czasu na kilku wspólnych spacerach przed adopcją by poznać swoją nową rodzinę, aby uniknąć nerwowych reakcji w nowym otoczeniu. Niestety niezbyt ładnie reaguje na ludzi ''przez kraty'' dlatego wiele osób mija jego boks szybkim krokiem i od 2018 roku nikt nie zainteresował się jego adopcją.', 2, 2);
INSERT INTO shelter.animals (id_animal, name, arrival_date, description, breed_id, size_id) VALUES (6, 'Hieronim', '2018-07-16', 'Bardzo przyjaźnie nastawiony do ludzi psiak, energiczny (ale nie nadpobudliwy). Jest nieco uzależniony od piłeczek, ale na szczęście ten nałóg nie jest szkodliwy ;) Hieronim jak do nas trafił tolerował psich kolegów, jednak w pewnym momencie konkurowanie o ludzką uwagę zmusiło nas do umieszczenia go w boksie pojedynczo.
Na spacer cieszy się wręcz szaleńczo, czasem w emocjach wtedy podszczypuje – chyba, że ma w pobliżu piłeczkę, którą może chwycić i na nią przerzucić część tej euforii.
Gdy już minie pierwsza radość spacerowa i potrzeba zabawy zostanie zaspokojona Hieronim biegnie do opiekuna by odpocząć, uwielbia być głaskany, a czasem stara się wcisnąć na kolana.
Niestety wiek i brak wyróżniania się pod względem np. wyglądu sprawia, że od lipca 2018 roku pozostaje niezauważany przez ludzi ...', 2, 3);
INSERT INTO shelter.animals (id_animal, name, arrival_date, description, breed_id, size_id) VALUES (7, 'Sierpień', '2018-08-01', 'Przyjęto go do schroniska 1.08.2018 r. po wypadku. Niestety, obrażenia były bardzo poważne - lekarze podjęli walkę o jego życie. Tu wygraliśmy - mimo, że Sierpień nie był łatwym pacjentem (agresja ) udało się, ale... .... uszkodzony został rdzeń kręgowy. W konsekwencji trzeba go ''odsikiwać'' , a kał ''gubi'' bezwiednie, dlatego zdrowa dieta jest szczególnie ważna. Sierpień regularnie jeździ na rehabilitacje ( tylne łapy nie utrzymują go, ale nie są calkiem bezwładne).

Psychicznie zmienił się bardzo i obecnie na wiekszość ludzi reaguje wybuchami radości. Wcześniej na wszystkich obcych reagował nieprzyjemnie. Niestety, gdy coś mu się nie spodoba - bywa niemiły. Jednak jeśli tylko bliżej się go pozna to nie jest nic z czym nie można sobie poradzić.

Opieka nad nim wymaga dużo zaangażowania - nauka odsikiwania, rehabilitacja, radzenie sobie z jego niezadowoleniem. On już tak dużo przeszedł , bólu i strachu, teraz dla równowagi po prostu należy mu się kochający dom...', 2, 3);
INSERT INTO shelter.animals (id_animal, name, arrival_date, description, breed_id, size_id) VALUES (8, 'Kuba', '2018-08-03', 'Spokojny, pewny siebie pies którego przed adopcją należy lepiej poznać. Jest nieufny w stosunku do obcych ludzi. Może zostawać sam w domu.
W stosunku do osób, które wiedzą jak z nim postępować jest miły, towarzyski i posłuszny.', 2, 5);
INSERT INTO shelter.animals (id_animal, name, arrival_date, description, breed_id, size_id) VALUES (9, 'Alex', '2018-10-30', 'Alex został do nas oddany w 2018 roku w bardzo złym stanie (ostatnie zdjęcie było zrobione w dniu przyjęcia do schroniska). Obecnie już wiemy, że jest alergikiem i dzięki właściwej diecie jest nie do poznania. Niestety, warunki w jakich był trzymany, brak normalnego konaktu z ludźmi nie pozostał bez wpływu na jego charakter. Jest psem wymagającycm doświadczonego, cierpliwego opiekuna. Najlepiej będzie czuł się w domu z ogrodem - jednak nie należy tego mylić z pozostawieniem go samemu sobie na podwórku. Jest bardzo energiczny, żądny przygód i inteligentny. W stosunku do obcych jest nieufny. Niestety u weterynarza czy przy zabiegach pielęgnacycjnych konieczny jest kaganiec.', 1, 5);
INSERT INTO shelter.animals (id_animal, name, arrival_date, description, breed_id, size_id) VALUES (10, 'Mrówka', '2019-01-25', 'Łobuz, nicpoń, trzpiot. Określenia te jak ulał pasują do Mrówki, który przypomina wyrośniętego z nagła młodzieniaszka niepotrafiącego zapanować jeszcze nad swym niezgrabnym ciałem, trochę niesfornego, ale jednocześnie bardzo inteligentnego i z reguły pozytywnie nastawionego do ludzi i innych zwierząt. Wymaga doświadczonego i cierpliwego opiekuna, zdecydowanego by poświęcić mu sporo uwagi. Warto jednak podjąć ten ''wysiłek'' i stać się przewodnikiem Mrówki – zasłużyć tym samym na nagrodę w postaci jego psiego uśmiechu i własnej satysfakcji z postępów i sukcesów w jego wychowaniu.

Brak wyuczonych manier, niepewność względem otaczającego Świata, lekka hiperaktywność sprawiają, że należy z nim postępować ostrożnie, cierpliwie i z wyczuciem. Ten fajny psiak wymaga poznania przed adopcją.', 2, 5);
INSERT INTO shelter.animals (id_animal, name, arrival_date, description, breed_id, size_id) VALUES (11, 'Stefan', '2019-07-01', 'Stefan został oddany do schroniska przez dotychczasowego właściciela. Nie wiemy, jak był przez niego traktowany, jednak wydaje się psem, który nie do końca wie, jak reagować na obecność człowieka. Z jednej strony, histerycznie szczekając, cieszy się z odwiedzin wolontariusza, z drugiej na wszelki wypadek z emocji powarkuje. Stefan jeszcze wiele musi się nauczyć - akceptowania smyczy, panowania nad emocjami, przełamania lęku przed dotykiem, na który czasem reaguje agresją. Przed nim sporo pracy, którą może ułatwić znajomość przez Stefka niektórych komend - np. "siad" - posłuszne oddawanie piłeczek czy pozytywny stosunek do i innych czworonogów.', 2, 3);
INSERT INTO shelter.animals (id_animal, name, arrival_date, description, breed_id, size_id) VALUES (12, 'Dżasper', '2016-05-12', 'Dżasper to dorosły pies w typie gończego polskiego. Jest mądry i pojętny, szybko się uczy. Gdy trafił do nas pierwszy raz był bardzo przerażony, chował się w budzie i potrzebował czasu na to by poczuć się bezpiecznie.
Lubi biegać, jest energiczny, ale równie chętnie przybiega na głaskanie i spędza czas z opiekunem (głaskanie lubi, jednak na jego zasadach). Potrafi dogadać się z nienatarczywymi suniami.. Może zostawać samemu w domu, choć w nowym miejscu potrzebuje chwili czasu by się zaaklimatyzować. Jest to pies ''pewny siebie'' który  potrzebuje konsekwentnego i doświadczonego opiekuna. Warto poznać go bliżej Dżasper potrafi być przemiły, kocha wędrówki – wierzymy, że gdzieś czeka na niego jego idealny dom.', 2, 4);